name: "1. Установка и настройка выбранной БД + ЯП"

on:
  push:
    branches:
      - main

jobs:
  check_hello_world_dir_not_empty:
    name: "Проверка наличия каталога ./hello_world/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
    
      - name: Url
        run: |
          dir="./hello_world/"
          if [ -d "${dir}" ]; then 
            if [ "$(ls -A ${dir})" ]; then
              echo "Предварительная проверка пройдена - каталог ${dir} создан и не пуст" >> $GITHUB_OUTPUT
 	    else
              echo "Предварительная проверка не пройдена - каталог ${dir} пуст" >> $GITHUB_OUTPUT
              exit 1
	    fi

          else 
            echo "Предварительная проверка не пройдена - каталог не найден ${dir}" >> $GITHUB_OUTPUT
            exit 1
          fi
