name: "3. Модель данных"

on:
  push:
    branches:
      - main
  gollum:

jobs:
  check_data_model:
    name: "Проверка нличия вики-страницы \"Модель данных\" и разделов \"Нереляционная модель\",  \"Реляционная модель\", \"Сравнение моделей\", \"Вывод\" в ней"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check wiki
        with:
          repository: ${{github.repository}}.wiki
      - name: check
        run: |
          page="Модель данных"
          nosql_model="Нереляционная модель"
          sql_model="Сценарий использования"
          comparison="Сравнение моделей"
          conclusion="Вывод"

          if ! [[ -f "${page}" ]]; then 
            echo "Предварительная проверка не пройдена - не найдена вики-страница \"Модель данных\"" >> $GITHUB_OUTPUT
            exit 1
          fi

          if ! cat "${page}" | grep -q "${nosql_model}"; then 
            echo "Предварительная проверка не пройдена - не найден заголовок ${nosql_model}" >> $GITHUB_OUTPUT
            exit 1
          fi


          if ! cat "${page}" | grep -q "${sql_model}"; then 
            echo "Предварительная проверка не пройдена - не найден заголовок ${sql_model}" >> $GITHUB_OUTPUT
            exit 1
          fi

          if ! cat "${page}" | grep -q "${comparison}"; then 
            echo "Предварительная проверка не пройдена - не найден заголовок ${comparison}" >> $GITHUB_OUTPUT
            exit 1
          fi

          if ! cat "${page}" | grep -q "${conclusion}"; then 
            echo "Предварительная проверка не пройдена - не найден заголовок ${conclusion}" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "Предварительная проверка пройдена - вики-страница найдена, нужные заголовки присутствуют " >> $GITHUB_OUTPUT
