name: "5. Прототип анализ"

on:
  push:
    branches:
      - main

jobs:
  check_hello_world_dir_not_empty:
    name: "Проверка наличия тега 0.5"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
        with:
          fetch-depth: 0
    
      - name: Build docker-compose
        run: |
          docker-compose build --no-cache

      - name: Run docker-compose
        run: |
          docker-compose up -d
          sleep 30

      - name: Check containers are alive
        run: |
          docker-compose ps --filter status=exited
          exited_count=`docker-compose ps --filter status=exited |  tail -n +2 | wc -l`

          docker-compose ps --filter status=dead
          dead_count=`docker-compose ps --filter status=dead |  tail -n +2 | wc -l`

          docker-compose ps --filter status=restarting
          restarting_count=`docker-compose ps --filter status=restarting |  tail -n +2 | wc -l`

          docker-compose ps --filter status=paused
          paused_count=`docker-compose ps --filter status=paused |  tail -n +2 | wc -l`

          docker-compose ps --filter status=created
          created_count=`docker-compose ps --filter status=created |  tail -n +2 | wc -l`
          
          if [[ "${exited_count}" != "0" ]] || [[ "${restarting_count}" != "0" ]] || [[ "${paused_count}" != "0" ]] || [[ "${created_count}" != "0" ]] || [[ "${created_count}" != "0" ]]; then
             echo "::error::Часть контейнеров не находится в состоянии running (завершили или не начали свою работу корректно) "
             exit 1
          fi 



      - name: check_tag
        run: |
          TAG="0.5"
          if [ $(git tag -l "${TAG}") ]; then
            echo "::notice::Тег ${TAG} найден"
          else
            echo "::error::Тег ${TAG} не найден"
            exit 1
          fi
